# Generated by Django 4.0.6 on 2022-11-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_beautician_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauticianphoto',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/beautician'),
        ),
    ]
