# Generated by Django 4.0.6 on 2022-11-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_beauticianphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauticianphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/beautician'),
        ),
    ]
