# Generated by Django 4.0.6 on 2022-11-10 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeauticianServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beautician')),
                ('services_id', models.ManyToManyField(blank=True, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='BeauticianAvailabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('beautician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beautician')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeauticianServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_api.beauticianavailabilities')),
                ('services_id', models.ManyToManyField(blank=True, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_name', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Panding', 'Panding'), ('Delete', 'Delete')], default='Panding', max_length=255)),
                ('appointment_service', models.ManyToManyField(blank=True, to='api.service')),
                ('beautician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_api.beauticianservices')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
