# Generated by Django 4.0.6 on 2022-11-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('client_api', '0002_alter_beauticianservices_beautician_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauticianservices',
            name='beautician_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.beautician'),
        ),
    ]
