# Generated by Django 4.0.6 on 2022-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0003_alter_beauticianservices_beautician_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Panding', 'Panding'), ('Rejected', 'Rejected')], default='Panding', max_length=255),
        ),
    ]
