# Generated by Django 4.0.6 on 2022-11-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0004_alter_appointmentmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='beautician_id',
            new_name='beautician',
        ),
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
