# Generated by Django 4.0.6 on 2022-11-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0005_rename_beautician_id_appointmentmodel_beautician_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='beautician',
            new_name='beautician_id',
        ),
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
