# Generated by Django 4.0.6 on 2022-11-15 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_beauticianphoto_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_api', '0006_rename_beautician_appointmentmodel_beautician_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, max_length=255)),
                ('review', models.TextField(blank=True, max_length=255, null=True)),
                ('beautician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beautician')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
