# Generated by Django 4.0.6 on 2022-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0007_ratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='rating',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, max_length=255),
        ),
    ]
