# Generated by Django 4.0.6 on 2022-11-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0008_alter_ratingmodel_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingmodel',
            old_name='beautician',
            new_name='beautician_id',
        ),
    ]
