# Generated by Django 4.0.6 on 2022-11-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_beauticianphoto_image'),
        ('client_api', '0011_alter_ratingmodel_beautician_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='beautician_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beautician'),
        ),
    ]
